version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'pwd'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'pwd'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3309:3306'
    expose:
      # Opens port 3306 on the container
      - '3309'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
